"""Domande del banco di prova del recupero (strumento recall), con le evidenze definite da regole sull'archivio.

Ogni domanda:
  id, db (archivio in bench/data/<db>.sqlite), split ('dev' per tarare, 'test' tenuto da parte: tutta la sessione
  nibble2 + alcune domande di G3 e prova-paging), ask (indice del messaggio della domanda: si cerca solo idx < ask),
  kind (valore | prima-versione | cronologia | ragionamento | esito), q (domanda), answer (risposta attesa),
  ev: gruppi di evidenza; OGNI gruppo deve essere coperto da almeno un pezzo restituito. Un gruppo è una regola
      {re: regex, role: ruolo (facoltativo), lo/hi: intervallo di idx (facoltativo)} risolta su TUTTI i pezzi
      dell'archivio che la soddisfano (copie equivalenti valgono tutte),
  queries: ricerche che un modello farebbe (testo libero, nell'ordine: simulano le chiamate, max 5),
  calls: chiamate strutturate facoltative (dict di argomenti per recall) usate dalle versioni che le supportano,
  para: True se la domanda è formulata con parole diverse dagli identificatori (controprova lessicale),
  neg: True se la risposta NON è nell'archivio (controllo negativo).
build_questions.py risolve le regole in id d'archivio -> questions.json (versionato).
"""

PP, G3, N2 = "prova-paging", "g3", "nibble2"

Q = [
    # ---------------- le 6 domande della prova di oggi (prova-paging) ----------------
    dict(id="pp-q1", db=PP, split="dev", ask=365, kind="esito",
         q="Nella primissima simulazione da riga di comando, quante vite erano rimaste alla fine e quanti nemici "
           "erano passati nell'ultima ondata?",
         answer="10/20 vite; nell'ondata 10 è passato 1 nemico (il boss, leak 10)",
         ev=[dict(re=r"VITTORIA — vite superstiti 10/20", role="tool", hi=40)],
         queries=["prima simulazione vite rimaste ultima ondata", "node sim/run.js --waves=10 --report",
                  "ESITO vite superstiti"],
         calls=[dict(query="ESITO vite superstiti", order="tempo")]),
    dict(id="pp-q2", db=PP, split="dev", ask=367, kind="esito",
         q="Su quale porta avevi avviato il server di sviluppo la prima volta, e quale indirizzo avevi usato per "
           "controllare che rispondesse?",
         answer="porta 5173 (PORT=5173 node server.js); controllo su http://127.0.0.1:5173/__health (fallito)",
         ev=[dict(re=r"PORT=5173 node server\.js", role="assistant-tool-args"),
             dict(re=r"127\.0\.0\.1:5173/__health", hi=70)],
         queries=["PORT=5173 node server.js", "server di sviluppo porta", "curl __health"]),
    dict(id="pp-q3", db=PP, split="dev", ask=369, kind="cronologia",
         q="Quando hai scritto render.js la prima volta c'era un errore di sintassi segnalato dal controllo: in che "
           "punto era e come l'hai corretto?",
         answer="la prima scrittura era pulita; l'errore (L748 Declaration or statement expected) è nell'edit "
                "successivo che aveva cancellato l'intestazione di roundRect",
         ev=[dict(re=r"L748: Declaration or statement expected", role="tool")],
         queries=["render.js errore di sintassi", "drawOverlays", "Declaration or statement expected"],
         calls=[dict(path="src/render.js", mode="timeline")]),
    dict(id="pp-q4", db=PP, split="dev", ask=847, kind="prima-versione",
         q="Quando hai scritto la primissima versione della configurazione, che oro iniziale avevi messo? Nel "
           "ragionamento avevi considerato un valore diverso prima di decidere?",
         answer="startGold 265 scritto (msg 20); nel ragionamento della stessa scrittura 'Player starts 240 gold'",
         ev=[dict(re=r"startGold:\s*265", role="assistant-tool-args", hi=21),
             dict(re=r"Player starts 240 gold|startGold 240", role="assistant-reasoning", hi=21)],
         queries=["startGold", "startGold: 300", "ECONOMIA E VITE", "startGold 300", "oro iniziale prima configurazione"],
         calls=[dict(path="src/config.js", mode="first", query="startGold")]),
    dict(id="pp-q5", db=PP, split="dev", ask=849, kind="cronologia",
         q="Che valori aveva il boss (vita, armatura, vite tolte) nella prima versione, prima che lo correggessi "
           "dopo la prima simulazione? E come sono cambiati?",
         answer="1600/16/10 (msg 20); poi 1450/16/10 (151), 1250/14/10 (155), 1150/14/10 speed 28 (165), "
                "... 1050/14/8 speed 27 (223)",
         ev=[dict(re=r"hp: 1600, speed: 30, armor: 16, bounty: 150, leak: 10", role="assistant-tool-args", hi=21),
             dict(re=r'"newText":"\s*hp: 1450', role="assistant-tool-args"),
             dict(re=r'"newText":"\s*hp: 1250', role="assistant-tool-args"),
             dict(re=r'"newText":"\s*hp: 1150', role="assistant-tool-args"),
             dict(re=r'"newText":"\s*hp: 1050', role="assistant-tool-args")],
         queries=["hp: 1600", "boss Colosso hp armor leak", "boss hp", "hp: 1450", "hp: 1050"],
         calls=[dict(path="src/config.js", mode="timeline", query="boss hp")]),
    dict(id="pp-q6", db=PP, split="dev", ask=853, kind="valore",
         q="L'oro iniziale della modalità difficile è uguale a quello che avevi messo all'inizio nella modalità "
           "normale?",
         answer="no: difficile 250, normale 265",
         ev=[dict(re=r"startGold:\s*250", role="assistant-tool-args"),
             dict(re=r"startGold:\s*265", role="assistant-tool-args", hi=21)],
         queries=["modalità difficile startGold", "startGold 250", "startGold 265"],
         calls=[dict(path="src/config.js", mode="first", query="startGold"), dict(query="hard startGold")]),
    # ---------------- nuove da prova-paging ----------------
    dict(id="pp-n1", db=PP, split="dev", ask=1000, kind="ragionamento",
         q="Perché il gate dello smoke test segnalava FALLITA anche quando il test riusciva?",
         answer="il DOM escapea le virgolette come &quot; e il pattern \"ok\":true non poteva mai combaciare",
         ev=[dict(re=r"&quot;", role="assistant|assistant-reasoning", lo=320, hi=330)],
         queries=["gate smoke test FALLITA", "bug nel gate virgolette", "&quot;"]),
    dict(id="pp-n2", db=PP, split="test", ask=1000, kind="ragionamento",
         q="Perché il server di sviluppo avviato in background non rispondeva al curl?",
         answer="il task in background gira in un namespace di rete isolato",
         ev=[dict(re=r"namespace", role="assistant|assistant-reasoning", hi=75)],
         queries=["server background curl non risponde", "namespace di rete isolato", "connessione rifiutata 5173"]),
    dict(id="pp-n3", db=PP, split="dev", ask=1000, kind="esito",
         q="Nella prima simulazione quale torre risultava quasi inutile, e con che numeri?",
         answer="la Tesla: 60 danni, 0 uccisioni",
         ev=[dict(re=r"60 dmg", lo=39, hi=39)],
         queries=["Tesla quasi inutile", "torre inutile simulazione", "Tesla dmg kill"]),
    dict(id="pp-n4", db=PP, split="dev", ask=1000, kind="esito",
         q="Quale errore JavaScript ha trovato il primo smoke test nell'harness, prima di 'view is not defined'?",
         answer="Uncaught TypeError: game.update is not a function",
         ev=[dict(re=r"game\.update is not a function", role="tool")],
         queries=["errore harness smoke test", "is not a function", "Uncaught TypeError"]),
    dict(id="pp-n5", db=PP, split="test", ask=1000, kind="esito",
         q="Il test post-fix risultava exit 1: quale errore c'era davvero?",
         answer="Uncaught ReferenceError: view is not defined (bug dell'harness)",
         ev=[dict(re=r"view is not defined", role="tool")],
         queries=["smoke test post-fix exit 1", "ReferenceError", "errore test post-fix"]),
    dict(id="pp-n6", db=PP, split="dev", ask=1000, kind="valore",
         q="Quale seed usava la simulazione CLI di default?",
         answer="20260101",
         ev=[dict(re=r"20260101")],
         queries=["seed simulazione", "seed default CLI", "sim seed"]),
    dict(id="pp-n7", db=PP, split="test", ask=1000, kind="ragionamento",
         q="Perché a un certo punto è stata aggiunta variabilità casuale alla simulazione?",
         answer="tutti i seed davano risultati identici (simulazione completamente deterministica)",
         ev=[dict(re=r"seed identici|All seeds identical", lo=179, hi=179)],
         queries=["variabilità simulazione", "seed identici deterministico", "speedJitter"]),
    dict(id="pp-n8", db=PP, split="dev", ask=1000, kind="valore",
         q="Quale valore sbagliato di startGold era finito nella modalità difficile (regressione trovata alla fine)?",
         answer="startGold: 32000 (doveva essere 250)",
         ev=[dict(re=r"startGold:\s*32000")],
         queries=["regressione oro modalità difficile", "startGold difficile sbagliato", "32000"]),
    dict(id="pp-n9", db=PP, split="dev", ask=1000, kind="cronologia",
         q="Qual è stata la prima modifica fallita (o applicata solo in parte) a src/config.js?",
         answer="msg 413: PARTIAL APPLY, edits[1] non trovato",
         ev=[dict(re=r"PARTIAL APPLY", role="tool", lo=413, hi=414)],
         queries=["config.js edit fallito", "PARTIAL APPLY config.js", "modifica fallita config"],
         calls=[dict(path="src/config.js", mode="timeline")]),
    dict(id="pp-n10", db=PP, split="test", ask=1000, kind="prima-versione",
         q="Nella prima stesura di config.js quanto valeva slowResist del boss, e a quanto è stato portato nella "
           "prima correzione?",
         answer="0.75, poi 0.65 (msg 151)",
         ev=[dict(re=r"slowResist: 0\.75", role="assistant-tool-args", hi=21),
             dict(re=r'"newText":"\s*hp: 1450.{0,80}slowResist: 0\.65', role="assistant-tool-args")],
         queries=["slowResist boss", "slowResist: 0.75", "slowResist 0.65"],
         calls=[dict(path="src/config.js", mode="timeline", query="slowResist")]),
    dict(id="pp-n11", db=PP, split="dev", ask=1000, kind="prima-versione", para=True,
         q="Quanto denaro aveva il giocatore all'inizio della partita nella prima stesura del bilanciamento?",
         answer="265",
         ev=[dict(re=r"startGold:\s*265", role="assistant-tool-args", hi=21)],
         queries=["denaro iniziale del giocatore", "soldi a inizio partita bilanciamento", "money at start"]),
    dict(id="pp-n12", db=PP, split="test", ask=1000, kind="ragionamento", para=True,
         q="In the very first engine test, how much gold did the player have after the first wave with no towers?",
         answer="299 (300 minus 1 early-call penalty)",
         ev=[dict(re=r"gold was 299", role="assistant-reasoning")],
         queries=["gold after first wave no towers", "first engine test gold", "early call penalty gold"]),
    dict(id="pp-n13", db=PP, split="dev", ask=1000, kind="valore",
         q="Come si chiama il gioco e chi è indicato come autore nell'intestazione di config.js?",
         answer="Cristalli di Guardia; Maurizio LastReload",
         ev=[dict(re=r"CRISTALLI DI GUARDIA.{0,400}LastReload|LastReload.{0,400}CRISTALLI", hi=25)],
         queries=["nome del gioco autore intestazione", "config.js intestazione autore", "Autore"],
         calls=[dict(path="src/config.js", mode="first")]),
    # ---------------- G3 (26 domande con risposte, archivio della prova paging) ----------------
    dict(id="g3-q01", db=G3, split="dev", ask=723, kind="prima-versione",
         q="Nella PRIMA versione di game.js (scritta verso le 05:20, prima di ogni ritocco di velocità), quanto "
           "valeva CFG.snakeBase (celle al secondo)?", answer="6.1",
         ev=[dict(re=r"snakeBase:\s+6\.1", hi=300)],
         queries=["CFG.snakeBase", "snakeBase prima versione game.js", "snakeBase"],
         calls=[dict(path="game.js", mode="first", query="snakeBase")]),
    dict(id="g3-q02", db=G3, split="dev", ask=723, kind="valore",
         q="Quanto vale CFG.comboWindow in game.js (secondi per mantenere la combo)?", answer="2.6",
         ev=[dict(re=r"comboWindow:\s+2\.6")],
         queries=["CFG.comboWindow", "comboWindow"]),
    dict(id="g3-q03", db=G3, split="dev", ask=723, kind="valore",
         q="Quanto vale CFG.powerDuration in game.js?", answer="8.5",
         ev=[dict(re=r"powerDuration:\s+8\.5")], queries=["CFG.powerDuration", "powerDuration"]),
    dict(id="g3-q04", db=G3, split="test", ask=723, kind="valore",
         q="Quanto vale CFG.shockRadius in game.js, e in che unità?", answer="4.6 celle",
         ev=[dict(re=r"shockRadius:\s+4\.6")], queries=["CFG.shockRadius", "shockRadius unità"]),
    dict(id="g3-q05", db=G3, split="dev", ask=723, kind="prima-versione",
         q="Qual era il valore iniziale di CFG.ghostBase (velocità base dei fantasmi) nella prima versione di "
           "game.js?", answer="4.9",
         ev=[dict(re=r"ghostBase:\s+4\.9")], queries=["CFG.ghostBase", "ghostBase prima versione"],
         calls=[dict(path="game.js", mode="first", query="ghostBase")]),
    dict(id="g3-q06", db=G3, split="dev", ask=723, kind="esito",
         q="Nella prima validazione dei labirinti in Node (verso le 06:17), quale seed aveva il LIVELLO 1? Dammi "
           "il numero esatto.", answer="27013482",
         ev=[dict(re=r"LIVELLO 1 seed 27013482", role="tool")],
         queries=["LIV 1 seed", "validazione labirinti LIVELLO 1 seed", "LIVELLO 1 seed"]),
    dict(id="g3-q07", db=G3, split="test", ask=723, kind="esito",
         q="Quale stringa di colore esatta veniva rifiutata da canvas (addColorStop) e faceva morire il loop di "
           "animazione?", answer="hsla(205 90% 40% 0.30)",
         ev=[dict(re=r"hsla\(205 90% 40% 0\.30?\)")],
         queries=["addColorStop could not be parsed as a color", "90% 40%", "colore rifiutato addColorStop"]),
    dict(id="g3-q08", db=G3, split="dev", ask=723, kind="esito",
         q="Quando Playwright non trovava il browser headless, quale eseguibile è stato usato al suo posto "
           "(percorso)?", answer="/usr/bin/google-chrome",
         ev=[dict(re=r"executablePath.{0,40}/usr/bin/google-chrome")],
         queries=["Playwright executablePath", "headless browser non trovato chromium", "executablePath"]),
    dict(id="g3-q09", db=G3, split="dev", ask=723, kind="esito",
         q="Quali versioni di Node e di Python sono state trovate nel primo controllo dell'ambiente?",
         answer="v24.18.0, Python 3.14.4",
         ev=[dict(re=r"v24\.18\.0\s+Python 3\.14\.4", role="tool")],
         queries=["node -v python3 -V", "versione node python", "Python 3"]),
    dict(id="g3-q10", db=G3, split="dev", ask=723, kind="esito",
         q="Qual era il titolo del task #6 creato nella todo list iniziale?",
         answer="Test headless with Playwright + screenshots",
         ev=[dict(re=r"Created #6:", role="tool")],
         queries=["todo task #6", "Created #6", "todo create"]),
    dict(id="g3-q11", db=G3, split="test", ask=723, kind="prima-versione",
         q="Nella primissima versione di game.js, come si chiamavano i fantasmi (nomi delle skin)? Elencali.",
         answer="ROSSO, ARANCIO, CIANO, MAGENTA",
         ev=[dict(re=r"name: 'ROSSO'", hi=22)],
         queries=["nomi fantasmi skins", "skins name fantasmi prima versione", "ghost skins"],
         calls=[dict(path="game.js", mode="first", query="skins name")]),
    dict(id="g3-q12", db=G3, split="dev", ask=723, kind="valore",
         q="Che tonalità (valore h) ha il fantasma FULGO?", answer="348",
         ev=[dict(re=r"h: 348, name: 'FULGO'")], queries=["FULGO", "FULGO h"]),
    dict(id="g3-q13", db=G3, split="dev", ask=723, kind="valore",
         q="Quali sono le coordinate delle POWER_CELLS definite in game.js?",
         answer="[2,2],[GRID-3,2],[2,GRID-3],[GRID-3,GRID-3]",
         ev=[dict(re=r"POWER_CELLS = \[\[2,2\]")], queries=["POWER_CELLS", "POWER_CELLS coordinate"]),
    dict(id="g3-q14", db=G3, split="dev", ask=723, kind="valore",
         q="Quanto vale la costante GS (scala del canvas di glow/bloom) in game.js?", answer="0.42",
         ev=[dict(re=r"GS = 0\.42")], queries=["const GS", "GS scala bloom glow", "GS ="]),
    dict(id="g3-q15", db=G3, split="test", ask=723, kind="cronologia",
         q="Quanti fps misurava tools/fps.js a 1280x800 subito prima e subito dopo l'ottimizzazione di buildLight "
           "(luce calcolata una volta per frame)?", answer="35 prima, 41 dopo",
         ev=[dict(re=r"1280x800 -> 35 fps|35 → 41|35→41|\(era 35\)"),
             dict(re=r"1280x800 -> 41 fps|35 → 41|35→41|41 fps\s+\(era 35\)")],
         queries=["tools/fps.js 1280x800", "fps buildLight", "1280x800 fps"]),
    dict(id="g3-q16", db=G3, split="dev", ask=723, kind="valore",
         q="Nel resoconto delle 08:17, quali percentuali over80 e over150 aveva lo screenshot 02-play?",
         answer="over80 7.53%, over150 2.53%",
         ev=[dict(re=r"7\.53")], queries=["over80 over150 02-play", "02-play over80", "over150"]),
    dict(id="g3-q17", db=G3, split="dev", ask=723, kind="valore",
         q="Quanti fantasmi ci sono al livello 1 (formula usata in loadLevel)?", answer="min(3+level,6) = 4",
         ev=[dict(re=r"Math\.min\(3 \+ level, 6\)")],
         queries=["loadLevel ghosts Math.min ghostCount", "numero fantasmi livello", "loadLevel fantasmi"]),
    dict(id="g3-q18", db=G3, split="dev", ask=723, kind="ragionamento",
         q="Perché all'inizio (verso le 05:20) la scrittura di game.js con lo strumento write falliva, e come è "
           "stato aggirato il problema?",
         answer="limite dei token di uscita -> scrittura a blocchi (write + append con heredoc)",
         ev=[dict(re=r"hit the output token limit", role="tool", hi=30),
             dict(re=r"heredoc", role="assistant-reasoning", hi=30)],
         queries=["write game.js fallita", "output token limit", "CHUNK_A", "heredoc append chunk"]),
    dict(id="g3-q19", db=G3, split="test", ask=723, kind="ragionamento",
         q="Perché tutti i colori hsla di game.js sono stati convertiti alla sintassi con le virgole?",
         answer="canvas rifiutava la sintassi senza virgole -> eccezione -> loop rAF morto",
         ev=[dict(re=r"could not be parsed as a color"), dict(re=r"sintassi con (le )?virgole|comma syntax")],
         queries=["colori hsla virgole", "hsla sintassi canvas", "comma syntax hsla"]),
    dict(id="g3-q20", db=G3, split="dev", ask=723, kind="ragionamento",
         q="Perché game.js viene caricato come script classico e non come modulo ES?",
         answer="i moduli ES su file:// falliscono per CORS",
         ev=[dict(re=r"CORS issues with file://|fail on file:// .{0,30}CORS", role="assistant-reasoning")],
         queries=["file://", "script classico modulo ES", "CORS moduli file"]),
    dict(id="g3-q21", db=G3, split="dev", ask=723, kind="ragionamento",
         q="Perché verso le 06:18 è stato rifatto il generatore di labirinti (prototipo 'a reticolo')?",
         answer="labirinti troppo aperti (piazze, pochi corridoi)",
         ev=[dict(re=r'troppo "aperti"|too open', lo=45, hi=55)],
         queries=["lattice maze corridors open plazas", "generatore labirinti reticolo", "labirinti troppo aperti"]),
    dict(id="g3-q22", db=G3, split="test", ask=723, kind="ragionamento",
         q="Perché è stato scritto tools/analyze.js?",
         answer="il modello non può vedere le immagini -> anteprima ASCII/statistiche dei pixel",
         ev=[dict(re=r"Non posso vedere le immagini", role="assistant", hi=100)],
         queries=["tools/analyze.js", "analyze.js perché", "anteprima ASCII screenshot"]),
    dict(id="g3-q23", db=G3, split="dev", ask=723, kind="ragionamento",
         q="Qual era il bug vero che faceva morire il serpente appena partiva (\"appena parte sbatto\") e perché "
           "accadeva?",
         answer="in resetSerpent !grid[nj][ni] era vero sulle celle libere perché OPEN vale 0",
         ev=[dict(re=r"OPEN vale|is OPEN \(value 0\)|cell is OPEN \(0\)")],
         queries=["resetSerpent bug", "appena parte sbatto", "!grid[nj][ni] OPEN"]),
    dict(id="g3-q24", db=G3, split="dev", ask=723, kind="ragionamento",
         q="Come è stata cambiata la regola della sterzata contro un muro, e perché?",
         answer="la svolta verso un muro resta in coda e si applica alla prima cella legale (scade ~1,1 s)",
         ev=[dict(re=r"intento resta in attesa|resta in coda e si esegue|pending-intent")],
         queries=["sterzata contro muro regola", "svolta muro coda intento", "MURO turn wall"]),
    dict(id="g3-q25", db=G3, split="test", ask=723, kind="cronologia",
         q="Quali sono le velocità finali del serpente (min e max, celle/s) e dei fantasmi?",
         answer="serpente 4.8 -> 9.2 celle/s, fantasmi 4.0",
         ev=[dict(re=r"4[.,]8 → 9[.,]2|4\.8→9\.2|snakeMax 11\.5 → 9\.2")],
         queries=["velocità finali serpente fantasmi", "snakeBase snakeMax ghostBase", "celle/s velocità"]),
    dict(id="g3-q26", db=G3, split="dev", ask=723, kind="valore",
         q="Quanto durano la pausa 'pronto' all'avvio e la 'grazia' iniziale?", answer="pronto 1,1 s; grazia 1,8 s",
         ev=[dict(re=r"grazia\*?\*?:? 1,8 s|grace 1\.8s|Grace: 1\.8s"),
             dict(re=r"pronto\*?\*?:?.{0,60}1,1 s|ready is 1\.1s|pause 1\.1s|1\.1s at level start")],
         queries=["pausa pronto grazia", "grazia iniziale secondi", "ready grace"]),
    # ---------------- nibble2 (tutta tenuta da parte: split test) ----------------
    dict(id="n2-01", db=N2, split="test", ask=1000, kind="esito",
         q="Che versione di Node c'era nell'ambiente di lavoro?", answer="v24.18.0",
         ev=[dict(re=r"v24\.18\.0", role="tool")], queries=["node -v", "versione Node ambiente"]),
    dict(id="n2-02", db=N2, split="test", ask=1000, kind="prima-versione",
         q="Quanto valeva LATTICE_STEP nella prima versione di maze.js, e a quanto è stato portato?",
         answer="3, poi 2 (msg 26)",
         ev=[dict(re=r"const LATTICE_STEP = 3;", role="assistant-tool-args", hi=20),
             dict(re=r'"newText":"const LATTICE_STEP = 2;"', role="assistant-tool-args")],
         queries=["LATTICE_STEP", "LATTICE_STEP maze.js prima versione"],
         calls=[dict(path="src/maze.js", mode="timeline", query="LATTICE_STEP")]),
    dict(id="n2-03", db=N2, split="test", ask=1000, kind="cronologia",
         q="Qual era il valore iniziale di SELF_IGNORE_ARC e quale valore ha risolto le morti sul proprio corpo?",
         answer="1.7, poi 2.05",
         ev=[dict(re=r"SELF_IGNORE_ARC = 1\.7", role="assistant-tool-args", hi=35),
             dict(re=r"SELF_IGNORE_ARC = 2\.05", role="assistant-tool-args")],
         queries=["SELF_IGNORE_ARC", "self-collision soglia arco"]),
    dict(id="n2-04", db=N2, split="test", ask=1000, kind="esito",
         q="Quanti pallini medi aveva il labirinto nella prima validazione con lo script di test?",
         answer="232.6 (zero vicoli ciechi)",
         ev=[dict(re=r"avg dots 232\.6", role="tool")],
         queries=["mazetest pallini medi", "avg dots", "validazione labirinto dots"]),
    dict(id="n2-05", db=N2, split="test", ask=1000, kind="cronologia",
         q="Che intensità aveva fx.shock quando si mangia un fantasma nella prima versione di main.js, e a quanto "
           "è stata ridotta?", answer="12, poi 9",
         ev=[dict(re=r"fx\.shock\(12, \[124, 249, 255\]\)", role="assistant-tool-args", hi=103),
             dict(re=r"fx\.shock\(9, \[124, 249, 255\]\)", role="assistant-tool-args")],
         queries=["fx.shock fantasma mangiato", "fx.shock(12", "shock ridotto"]),
    dict(id="n2-06", db=N2, split="test", ask=1000, kind="valore",
         q="Su che porta girava il server statico usato per i test nel browser?", answer="8123",
         ev=[dict(re=r"8123")], queries=["server statico porta", "serve.mjs porta", "tools/serve.mjs"]),
    dict(id="n2-07", db=N2, split="test", ask=1000, kind="esito",
         q="Che punteggio e che lunghezza ha raggiunto l'autopilota dopo la correzione della collisione con sé "
           "stesso?", answer="score 35880, len 59",
         ev=[dict(re=r"score: 35880|score 35880|35880")],
         queries=["autopilot score len", "sim score lunghezza autopilota", "score len 59"]),
    dict(id="n2-08", db=N2, split="test", ask=1000, kind="esito",
         q="Dove si trovava l'immagine di riferimento che l'utente voleva far vedere?",
         answer="su AI395, /home/mverde/Immagini/nibbles.jpeg",
         ev=[dict(re=r"/home/mverde/Immagini/nibbles\.jpeg", role="user")],
         queries=["immagine riferimento utente", "nibbles.jpeg", "AI395 Immagini"]),
    dict(id="n2-09", db=N2, split="test", ask=1000, kind="ragionamento",
         q="Perché l'assistente credeva che un'altra sessione avesse riscritto game.js?",
         answer="trovava costanti che non ricordava di aver scritto (TURN_ASSIST, SELF_IGNORE_ARC...): i suoi "
                "messaggi vecchi erano nascosti",
         ev=[dict(re=r"I did NOT write|I did not write", role="assistant-reasoning")],
         queries=["altra sessione game.js riscritto", "I did not write these", "game.js riscritto"]),
    dict(id="n2-10", db=N2, split="test", ask=1000, kind="esito",
         q="Che errore c'era nel colore wallTop del tema NEON GRID?", answer="'#2c4straight' (non è un colore)",
         ev=[dict(re=r"#2c4straight")], queries=["wallTop NEON GRID", "wallTop colore tema"]),
    dict(id="n2-11", db=N2, split="test", ask=1000, kind="valore",
         q="Qual è la formula della velocità dei fantasmi per livello?", answer="4.3 + (level-1)*0.28",
         ev=[dict(re=r"ghostSpeed = 4\.3 \+ \(level - 1\) \* 0\.28")],
         queries=["ghostSpeed", "velocità fantasmi livello", "ghostSpeed formula"]),
    dict(id="n2-12", db=N2, split="test", ask=1000, kind="ragionamento",
         q="Perché è stato aggiunto un probe che misura i pixel del canvas?",
         answer="il modello non può vedere le immagini",
         ev=[dict(re=r"Non posso vedere le immagini|I can't see images", lo=118, hi=122)],
         queries=["probe pixel canvas", "verifica render immagini", "probe automatico"]),
    dict(id="n2-13", db=N2, split="test", ask=1000, kind="esito", para=True,
         q="Quante cariche speciali per vita ha il giocatore per rispedire indietro i nemici?",
         answer="tre soffi per vita",
         ev=[dict(re=r"Tre soffi per vita|3 charges|tre soffi")],
         queries=["cariche speciali per vita", "rispedire indietro nemici potere", "abilità rimanda fantasmi"]),
    dict(id="n2-14", db=N2, split="test", ask=1000, kind="valore",
         q="Quale tasto attiva il soffio?", answer="F o Shift (pulsante SOFFIO su touch)",
         ev=[dict(re=r"\*\*`F`\*\* o \*\*`Shift`\*\*|KeyF", role="assistant|assistant-tool-args")],
         queries=["tasto soffio", "soffio tasto F Shift", "SOFFIO"]),
    dict(id="n2-15", db=N2, split="test", ask=1000, kind="esito",
         q="Che errore ha dato tools/death.mjs la prima volta?", answer="TypeError: g.maze.row is not a function",
         ev=[dict(re=r"g\.maze\.row is not a function", role="tool")],
         queries=["tools/death.mjs errore", "death.mjs TypeError", "is not a function"]),
    dict(id="n2-16", db=N2, split="test", ask=1000, kind="esito",
         q="Che errore dava Chrome headless al primo tentativo di screenshot?",
         answer="Failed to create a unique user data directory for headless",
         ev=[dict(re=r"unique user data directory", role="tool")],
         queries=["chrome headless errore screenshot", "google-chrome headless errore", "user data directory"]),
    dict(id="n2-17", db=N2, split="test", ask=1000, kind="esito", para=True,
         q="When the user asked whether he could try the game himself, what frame rate did the assistant report?",
         answer="60 fps (server http://127.0.0.1:8123)",
         ev=[dict(re=r"60 fps", role="assistant", lo=570, hi=580)],
         queries=["user try game frame rate", "posso provarlo anche io", "fps server attivo"]),
    dict(id="n2-18", db=N2, split="test", ask=1000, kind="ragionamento",
         q="All'inizio il serpente moriva su sé stesso: che problema aveva la trail?",
         answer="non teneva conto della posizione continua della testa: la coda si estendeva nella direzione sbagliata",
         ev=[dict(re=r"trail non teneva conto", role="assistant")],
         queries=["trail serpente muore su sé stesso", "trail posizione testa", "bug trail coda"]),
    # ---------------- controlli negativi (risposta assente) ----------------
    dict(id="neg-01", db=PP, split="dev", ask=1000, kind="negativo", neg=True,
         q="Su che porta girava il server WebSocket del multiplayer?", answer=None, ev=[],
         queries=["WebSocket multiplayer porta", "server multiplayer"]),
    dict(id="neg-02", db=PP, split="dev", ask=1000, kind="negativo", neg=True,
         q="Quale versione di Phaser è stata installata?", answer=None, ev=[],
         queries=["Phaser versione", "npm install phaser"]),
    dict(id="neg-03", db=G3, split="dev", ask=723, kind="negativo", neg=True,
         q="Qual era il punteggio record salvato nel database PostgreSQL?", answer=None, ev=[],
         queries=["PostgreSQL record punteggio", "database highscore"]),
    dict(id="neg-04", db=G3, split="dev", ask=723, kind="negativo", neg=True,
         q="Con quale comando è stato fatto il deploy su Vercel?", answer=None, ev=[],
         queries=["deploy Vercel", "vercel deploy comando"]),
    dict(id="neg-05", db=PP, split="test", ask=1000, kind="negativo", neg=True,
         q="Quale libreria audio (Howler.js) è stata usata per i suoni delle torri?", answer=None, ev=[],
         queries=["Howler.js suoni torri", "libreria audio howler"]),
    dict(id="neg-06", db=G3, split="test", ask=723, kind="negativo", neg=True,
         q="Quante stelle aveva il repository GitHub del progetto?", answer=None, ev=[],
         queries=["GitHub stelle repository", "github stars"]),
    dict(id="neg-07", db=N2, split="test", ask=1000, kind="negativo", neg=True,
         q="Qual era l'indirizzo della classifica online dei punteggi (leaderboard)?", answer=None, ev=[],
         queries=["leaderboard classifica online", "classifica punteggi indirizzo"]),
    dict(id="neg-08", db=N2, split="test", ask=1000, kind="negativo", neg=True,
         q="In che formato WebP sono state convertite le texture dei muri?", answer=None, ev=[],
         queries=["WebP texture muri", "conversione webp"]),
]
